#!/bin/sh

# Copyright (c) 2018 ARM Ltd.
#
# SPDX-License-Identifier: Apache-2.0


### BEGIN INIT INFO
# Provides:       mbl-app-update-manager
# Required-Start: $local_fs $time
# Required-Stop: $local_fs $time
# Should-Start:
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop:  0 1 2 6
# Short-Description: Starts and stops mbl-app-update-manager-daemon
# Description: Starts and stops the shell script that awaits for app updates notification to perform package installation
### END INIT INFO

init_script="$0"
name=mbl-app-update-manager-daemon
daemon="/usr/bin/${name}"

exit_with_usage() {
    echo "Usage: ${init_script} {start}" 1>&2
    exit "$1"
}

do_start() {
    echo "Starting ${name}..." 1>&2
    start-stop-daemon --start --quiet --background --exec "$daemon"
    case "$?" in
        0)
            echo "${name} started" 1>&2
            return 0
            ;;
        1)
            echo "${name} is already running" 1>&2
            return 0
            ;;
        *)
            echo "Failed to start ${name}" 1>&2
            return 1
            ;;
    esac
}


if [ "$#" -ne 1 ]; then
    exit_with_usage 2
fi

if ! [ -x "$daemon" ]; then
    echo "${daemon} is not an executable file" 1>&2
    exit 5
fi

case "$1" in
    start)
        do_${1}
        exit $?
        ;;
    stop|status)
        # The use of the --exec option with interpreted scripts causes the
        # implementation of these commands to not work as intended.
        exit_with_usage 3
        ;;
    *)
        exit_with_usage 2
        ;;
esac

# Shouldn't get here
exit 1
