#!/bin/bash
# Copyright (c) 2018 Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

set -e

# The length of the path to the python binary in mbed's shebang line can
# exceed the kernel's limit. Hack around this by reading it manually

wrapped_mbed_path="__REPLACE_ME_WITH_WRAPPED_MBED_PATH__"
shebang="$(head -1 "$wrapped_mbed_path")"
cmd="${shebang#\#\!}"

# A shebang line (on Linux at least) contains an interpreter/executable without
# spaces and a single optional argument (which may contain spaces)
read -r interpreter arg < <(printf "%s\n" "${cmd}")
if [ -n "$arg" ]; then
    exec "$interpreter" "$arg" "$wrapped_mbed_path" "$@"
else
    exec "$interpreter" "$wrapped_mbed_path" "$@"
fi
